apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: quote-api-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: quote-api.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: quote-api-svc
                port:
                  number: 80
